name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Action 🎉 triggered by a ${{ github.event_name }} event, now running on a ${{ runner.os }}. Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Check out repository code
      uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v9
      with:
        name: mycache

    - run: nix-build
    - run: nix-shell --run "echo OK"

    - uses: meeDamian/github-release@2.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "automatic-bin"
          files: result/bin
